config:
  partial_parse: true
  use_colors: true

gmi_common_dbt_utils:
  target: default
  outputs:
    default:
      dataset: "{{ env_var('BIGQUERY_DATASET')}}"
      fixed_retries: 1
      location: "{{ env_var('BIGQUERY_LOCATION')}}"
      method: "{{ env_var('BIGQUERY_AUTH_METHOD')}}"
      priority: interactive
      project: "{{ env_var('BIGQUERY_PROJECT_ID')}}"
      threads: 4
      timeout_seconds: 300
      type: bigquery
  
